const action_types = {
  POST_INVENTORY: 'POST_INVENTORY',
  GET_PRODUCT_TYPES: 'GET_PRODUCT_TYPES',
  ADD_INVENTORY_ITEMS: 'ADD_INVENTORY_ITEMS',
  REQUEST_INVENTORY_SUCCESS: 'REQUEST_INVENTORY_SUCCESS',
  GET_INVENTORY_REQUESTS_SUCCESS: 'GET_INVENTORY_REQUESTS_SUCCESS',
  INVENTORY_REQUEST_RECEIVED: 'INVENTORY_REQUEST_RECEIVED',
  INVENTORY_REQUEST_MADE: 'INVENTORY_REQUEST_MADE',
  GET_REQUESTED_INVENTORY_SUCCESS: 'GET_REQUESTED_INVENTORY_SUCCESS',
  ACCEPT_REQUEST_SUCCESS: 'ACCEPT_REQUEST_SUCCESS',
  ACCEPT_REQUEST_EVENT_RECEIVED: 'ACCEPT_REQUEST_EVENT_RECEIVED',
};
export default action_types;
